name: sdwalls
description: A beautiful responsive wallpaper app with auto-update functionality 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Network
  http: ^1.2.0
  dio: ^5.4.0

  # State Management
  provider: ^6.1.1

  # Wallpaper Management
  wallpaper_manager_flutter: ^1.0.1

  # Background Services
  flutter_background_service: ^5.0.0

  # Notifications
  # flutter_local_notifications: ^17.0.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Splash Screen
  flutter_native_splash:

  # Image Caching
  cached_network_image: ^3.3.1

  # Path Provider
  path_provider: ^2.1.2

  # URL Launcher
  url_launcher: ^6.2.1

  # Sharing
  share_plus: ^7.2.2

  # SVG rendering
  flutter_svg: ^2.0.9

  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#1a1a1a"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#1a1a1a"
  fullscreen: true

msix_config:
  display_name: SDwalls
  publisher_display_name: Somnath Dash
  identity_name: Somnath Dash
  msix_version: 1.0.11.0
  publisher: Somnath Dash
  store: true
  logo_path: D:\Apps\sdwalls\assets\logo.png # WARNING THIS PATH IS FROM YOUR DISK, NOT FROM PROJECT, READ MSIX DOC FOR MORE INFO
  trim_logo: false

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  windows: 
    generate: true
    image_path: "assets/logo.ico"
    icon_size: 50